name: Auto Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # يقوم بالتحقق من التحديثات يومياً عند منتصف الليل
  workflow_dispatch: # يسمح لك بتشغيل المزامنة يدوياً من زر في جيتهاب

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        ref:  main # تأكد أن الفرع الرئيسي اسمه main
        fetch-depth: 0

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: amElnagdy/basarai # رابط المطور الأصلي

    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
